### ISSUE TITLE
[Feature] Create Block/Blacklist and allow all users to edit & remove their own Birthdays

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBotSapphire#87]
### Currently
User can register their Birthday once. Update & Remove of Birthdays is only possible to users with `ManageRoles` permissions.

### Description
All users can edit and remove their birthdays as much as they want. To prevent users from using this with bad intention, we want to provide a blocklist that stops users on this list from using using `update` `register` and `remove` birthdays.

### Done
- [x] Create Database Model for this list
### ToDo
- [ ] Decided on naming (`blocklist` or `blacklist`)
- [ ] Create  API Endpoints
- - add
- - retrieve
- - remove
- [ ] Create blocklist command
- - add
- - remove
- - list
 - [ ] Update Documentation for this feature
