### ISSUE TITLE
[Improvement] Refactor API Endpoints

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBotSapphire#88]
Currently, all API Responses handle Errors differently. This leads to confusion and bad code practice.

### ToDo's
- [ ] Add ApiVerification to all endpoints
- [ ] Respond with 200 if Duplicate user and populate error object
- [ ] Refactor Error Responses
``` js
// Add a success boolean, and an optional error object.
return response.status(400).json({ success: false, error: { code: 'missing_parameter', message: 'Missing Parameter - user_id' } });
```
- [ ] Create ErrorCode Enum with all Enums

**Comment by nikolaischunk** [comment]
Example of a good Implemented Endpoint: [Birthday Create Endpoint](https://github.com/BirthdayyBot/BirthdayyBotSapphire/blob/develop/src/routes/birthday/create/index.ts)

**Comment by Swiizyy** [comment]
For apiVerification here is an example here 🙂

https://github.com/skyra-project/skyra/blob/main/src/lib/api/utils.ts

**Comment by Swiizyy** [comment]
And do not use the status function but directly the functions for example (badRequest())

**Comment by Swiizyy** [comment]
Creation of types for each route to best manage returns in orders and others

**Comment by Swiizyy** [comment]
If it wasn't done when I get home from work I'll take care of it 🙂
